[package]
name = "valeria_nifnative"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "valeria_nifnative"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.1"
lazy_static = "1.4.0"